stages:
  - precheck
  - preparation
  - sync
  - tagging
  - deployment

sync_precheck:
  stage: precheck
  tags: [shell]
  script:
    - chmod +x ci/bin/exist.sh
    - ci/bin/exist.sh
  artifacts:
    paths:
      - svn
    expire_in: 1 day

svn_checkout:
  tags: [docker]
  stage: preparation
  image:
    name: jgsqware/svn-client
    entrypoint: ["/bin/sh", "-c"]
  script:
    - svn co --username=${WP_USERNAME} "${WP_REPO}" svn
    - cd svn/
    #- svn revert .
    - svn status
  artifacts:
    paths:
      - svn
    expire_in: 1 day
  only:
    - /master/

sync_changes:
  tags: [docker]
  stage: sync
  image: luky/rsync
  script:
    - ci/bin/sync_with_trunk.sh
    - ci/bin/change_version.sh
  dependencies:
    - svn_checkout
  artifacts:
    paths:
      - svn
    expire_in: 1 day
  only:
    - /master/

pack_bundle:
  stage: deployment
  tags: [shell]
  script:
    - ci/bin/pack.sh
  artifacts:
    paths:
      - keitaro.zip
    expire_in: 6 day
  dependencies:
    - sync_changes
  only:
    - /master/

tag_commit:
  stage: tagging
  tags: [shell]
  script:
    - ci/bin/tag.sh
  dependencies:
    - sync_changes
  only:
    - /master/

svn_commit:
  stage: deployment
  tags: [docker]
  image:
    name: jgsqware/svn-client
    entrypoint: ["/bin/sh", "-c"]
  script:
    - export APP_VERSION=$(cat VERSION)
    - cd svn
    - svn status
    - svn add --force --parents ./assets/* ./trunk/*
    - svn ci -m "Release ${APP_VERSION}" --username "${WP_USERNAME}" --password "${WP_PASSWORD}" --no-auth-cache
  dependencies:
    - sync_changes
  only:
    - /master/
  #when: manual
  allow_failure: false
