before_script:
  - ci/bin/init_svn.sh
  - ci/bin/version.sh

stages:
  - preparation
  - sync
  - tagging
  - deployment

svn_checkout:
  stage: preparation
  tags: [docker]
  image: jgsqware/svn-client
  script:
    - co --username=${WP_USERNAME} "${WP_REPO}" svn
  artifacts:
    paths:
      - svn
  only:
    - /master/

sync_changes:
  tags: [docker]
  stage: sync
  image: luky/rsync
  script:
    - ci/bin/sync_with_trunk.sh
    - ci/bin/change_version.sh
  dependencies:
    - svn_checkout
  artifacts:
    paths:
      - svn

pack_bundle:
  stage: deployment
  tags: [shell]
  script:
    - ci/bin/pack.sh
  artifacts:
    paths:
      - keitaro.zip
  dependencies:
    - sync_changes
  only:
    - /master/

tag_commit:
  stage: tagging
  tags: [shell]
  script: ci/bin/tag.sh
  dependencies:
    - sync_changes
  only:
    - /master/

svn_commit:
  stage: deployment
  tags: [docker]
  image:
    name: jgsqware/svn-client
    entrypoint: ["/bin/sh", "-c"]
  script:
    - export commit_msg="Release ${APP_VERSION}"
    - add ./assets/* ./trunk/*
    - ci -m ${commit_msg} --username "${WP_USERNAME}" --password "${WP_PASSWORD}" --no-auth-cache
  dependencies:
    - sync_changes
  only:
    - /master/
  #when: manual
  allow_failure: false
